//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBC_Report
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public int reportId { get; set; }
        public string BloodGroup { get; set; }
        public decimal RBC_count { get; set; }
        public decimal WBC_count { get; set; }
        public decimal Hemoglobin { get; set; }
        public decimal Hematrocit { get; set; }
        public int platelet { get; set; }
    }
}
